c_compiler_version:
  - 13

cxx_compiler_version:
  - 13

cuda_compiler:
  - cuda-nvcc

cmake_version:
  - ">=3.30.4"

scikit_build_core_version:
  - ">=0.10.0"

c_stdlib:
  - sysroot

c_stdlib_version:
  - "2.28"
