# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: ${{ git.head_rev(".")[:8] }}

package:
  name: cugraph-dgl
  version: ${{ version }}

source:
  path: ../../..

build:
  string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh cugraph-dgl

requirements:
  host:
    - pip
    - python =${{ py_version }}
    - rapids-build-backend >=0.3.0,<0.4.0.dev0
    - setuptools>=61.0.0
  run:
    - cugraph =${{ minor_version }}
    - cupy >=13.2.0
    - dgl >=2.4.0.th24.cu
    - numba >=0.57
    - numpy >=1.23,<3.0a0
    - pandas
    - python
    - pytorch >=2.3
    - tensordict >=0.1.2

tests:
  - python:
      imports: cugraph_dgl
      pip_check: false

about:
  homepage: ${{ load_from_file("python/cugraph-dgl/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cugraph-dgl/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/cugraph-dgl/pyproject.toml").project.description }}
