# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cugraph-pyg
  version: ${{ version }}

source:
  path: ../../..

build:
  string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh cugraph-pyg --allgpuarch

requirements:
  host:
    - pip
    - python =${{ py_version }}
    - rapids-build-backend >=0.4.0,<0.5.0
    - setuptools>=77.0.0
  run:
    - cupy >=13.6.0
    - numpy >=1.23,<3.0
    - packaging
    - pandas
    - pylibcugraph =${{ minor_version }}
    - pylibwholegraph =${{ minor_version }}
    - python
    - pytorch-gpu >=2.3
    - pytorch_geometric >=2.5,<2.7

tests:
  - python:
      imports: cugraph_pyg
      pip_check: false

about:
  homepage: ${{ load_from_file("python/cugraph-pyg/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cugraph-pyg/pyproject.toml").project.license }}
  summary: ${{ load_from_file("python/cugraph-pyg/pyproject.toml").project.description }}
