# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cugraph-pyg
  version: ${{ version }}

source:
  path: ../../..

build:
  string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh cugraph-pyg --allgpuarch

requirements:
  build:
    - ${{ stdlib("c") }}
  host:
    - cython >=3.0.0
    - pip
    - python =${{ py_version }}
    - rapids-build-backend >=0.3.0,<0.4.0.dev0
    - setuptools>=61.0.0
  run:
    - cugraph =${{ minor_version }}
    - cupy >=13.2.0
    - numba >=0.57
    - numpy >=1.23,<3.0a0
    - pandas
    - pylibwholegraph =${{ minor_version }}
    - python
    - pytorch >=2.3
    - pytorch_geometric >=2.5,<2.7
    - tensordict >=0.1.2
  ignore_run_exports:
    by_name:
      - cuda-version

tests:
  - python:
      imports: cugraph_pyg
      pip_check: false

about:
  homepage: ${{ load_from_file("python/cugraph-pyg/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cugraph-pyg/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/cugraph-pyg/pyproject.toml").project.description }}
