# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

recipe:
  name: libwholegraph-split

cache:
  source:
    path: ../../..

  build:
    script:
      content: |
        # Remove `-fdebug-prefix-map` line from CFLAGS and CXXFLAGS so the
        # incrementing version number in the compile line doesn't break the
        # cache
        set -x
        export CFLAGS=$(echo $CFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
        export CXXFLAGS=$(echo $CXXFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
        set +x

        ./build.sh -n libwholegraph tests -v --allgpuarch
      secrets:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
      env:
        CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
        CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
        CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
        CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
        PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL") }}
        SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
        SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
        SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
        SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
        SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
        SCCACHE_S3_KEY_PREFIX: libwholegraph/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}

  requirements:
    build:
      - ${{ compiler("c") }}
      - ${{ compiler("cxx") }}
      - ${{ compiler("cuda") }} =${{ cuda_version }}
      - cuda-version =${{ cuda_version }}
      - cmake ${{ cmake_version }}
      - ninja
      - ${{ stdlib("c") }}
    host:
      - cuda-version =${{ cuda_version }}
      - doxygen ${{ doxygen_version }}
      - libraft =${{ minor_version }}
      - libraft-headers =${{ minor_version }}
      - librmm =${{ minor_version }}
      - nccl ${{ nccl_version }}
      - if: cuda_major == "11"
        then:
          - cudatoolkit
        else:
          - cuda-cudart-dev
          - cuda-driver-dev
          - cuda-nvml-dev

outputs:
  - package:
      name: libwholegraph
      version: ${{ version }}
    build:
      script:
        content: |
          cmake --install cpp/build
      dynamic_linking:
        overlinking_behavior: "error"
        missing_dso_allowlist:
          - libcuda.so.1
          - libnvidia-ml.so.1
      prefix_detection:
        ignore:
          # See https://github.com/rapidsai/build-planning/issues/160
          - lib/libwholegraph.so
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - cuda-version =${{ cuda_version }}
        - librmm =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - if: cuda_major == "11"
          then:
            - cudatoolkit
          else:
            - cuda-cudart-dev
            - cuda-driver-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - if: cuda_major == "11"
          then:
            - cudatoolkit
          else:
            - cuda-cudart
        - libraft =${{ minor_version }}
        - nccl ${{ nccl_version }}
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-version
          - librmm
          - nccl
          - if: cuda_major == "11"
            then:
              - cudatoolkit
    about:
      homepage: https://rapids.ai
      license: Apache-2.0
      summary: libwholegraph library

  - package:
      name: libwholegraph-tests
      version: ${{ version }}
    build:
      script:
        content: |
          cmake --install cpp/build --component testing
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - cuda-version =${{ cuda_version }}
        - ${{ pin_subpackage('libwholegraph', exact=True) }}
        - if: cuda_major == "11"
          then: cudatoolkit
          else:
            - cuda-cudart-dev
            - cuda-driver-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - ${{ pin_subpackage('libwholegraph', exact=True) }}
        - if: cuda_major == "11"
          then: cudatoolkit
          else: cuda-cudart
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-version
          - librmm
          - nccl
          - if: cuda_major == "11"
            then: cudatoolkit
    about:
      homepage: https://rapids.ai
      license: Apache-2.0
      summary: libwholegraph tests
